#!/bin/bash
curdir=`pwd`
version=$(./version)
ver=$(echo $version | cut -d "-" -f1)
mkdir -p /tmp/pptpd-$ver
cp -ar * /tmp/pptpd-$ver/
cd /tmp
tar -czf /usr/src/redhat/SOURCES/pptpd-$version.tar.gz pptpd-$ver
cd $curdir
rpmbuild -bb pptpd.spec
